name: Server CI/CD Pipeline

on:
  pull_request:
    branches:
      - '**'  # Run on all PRs
  push:
    branches:
      - main  # Run on push to main (build/deploy)

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Cache Node Modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: npm ci

      - name: Run Linter
        run: npm run lint

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Cache Node Modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests and Check Coverage
        run: |
          COVERAGE_OUTPUT=$(npx jest --coverage --coverageThreshold='{"global": {"branches": 50, "functions": 50, "lines": 50, "statements": 50}}')
          echo "$COVERAGE_OUTPUT"
          if echo "$COVERAGE_OUTPUT" | grep -q "Test Suites: .* failed"; then
            echo "Some test suites failed."
            exit 1
          fi
          if echo "$COVERAGE_OUTPUT" | grep -q "Test coverage does not meet requirements"; then
            echo "Test coverage does not meet requirements."
            exit 1
          fi
          echo "Test coverage meets requirements."

  build:
    name: Build Project
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install and Build
        run: |
          npm ci
          npm run build
